import { Header } from '@/components/Header'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'
import { ContainerPage } from '@/components/ContainerPage'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Igor D. Rangel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ptbr">
      <body className={inter.className}>
        <ContainerPage>
          <Header />
          {children}
        </ContainerPage>
      </body>
    </html>
  )
}
